### ISSUE TITLE
Inference example

### ISSUE THREAD

**Issue by DaniyarM** [ShirleyMaxx/ContextPose-PyTorch-release#1]
Hello, could you please provide an inference example for any .mp4 video file? It not clear from your code how to do that - it seems that it only can evaluate Human3.6M dataset...

**Comment by ShirleyMaxx** [comment]
Hi, thanks for your attention.

At this time, our method couldn't inference ANY video without root information (locate back-projected volume) or camera parameter (used when doing back-projection).
